// Wraps @opencode-ai/sdk for sending a developer prompt to an existing per-run
// opencode session and collecting back the assistant text + token usage.
//
// The per-run server is started by the workflow's startRunOpencode activity
// (Task 5). We resolve port/password from the backend, lazily create or reuse
// the developer session via the backend's session-ensure endpoint, send the
// prompt directly to the opencode HTTP server using the SDK, and return a
// stable result shape.
//
// ----------------------------------------------------------------------------
// SDK SHAPE NOTES — discovered from @opencode-ai/sdk@1.14.25
// ----------------------------------------------------------------------------
// The SDK is auto-generated by @hey-api/openapi-ts and differs from the plan
// snippet. Key facts a future maintainer needs:
//
//   * Import: `import { createOpencodeClient, type OpencodeClient } from '@opencode-ai/sdk'`
//     There is also `new OpencodeClient(...)` exported, but it expects an
//     internal `_HeyApiClient` instance — the supported entry point is the
//     factory `createOpencodeClient(config)`.
//
//   * Constructor config (`Config & { directory?: string }`):
//       - `baseUrl: string`              — e.g. "http://127.0.0.1:<port>"
//       - `headers?: Record<...>`        — used here for Basic auth
//       - `auth?: AuthToken | (auth) => ...` — only relevant for endpoints
//                                              that declare a security scheme;
//                                              opencode serve uses Basic auth
//                                              and the OpenAPI doesn't declare
//                                              that scheme, so we add the
//                                              Authorization header directly.
//
//   * Send a message: `client.session.prompt({ path: { id }, body: { parts, model? } })`
//     - `path.id` is the session ID
//     - `body.parts` is `Array<TextPartInput | FilePartInput | ...>` —
//       a plain text prompt becomes `[{ type: 'text', text: '...' }]`
//     - `body.model` is `{ providerID: string; modelID: string }` (NOT a
//       slash-separated string). We parse "primary/MiniMax-M2.7" into the
//       struct form.
//
//   * Response shape (default responseStyle is "fields"):
//       { data: { info: AssistantMessage; parts: Part[] } | undefined,
//         error: ... | undefined,
//         request, response }
//     - `info` is an AssistantMessage with `cost: number` and
//       `tokens: { input, output, reasoning, cache: { read, write } }`.
//     - `parts` is a Part[] union. The assistant's plain reply lives in
//       parts whose `type === 'text'`; we concatenate all text parts.
//
// SDK upgrades only need this file edited; downstream callers (Task 7) depend
// on the ServeMessageInput / ServeMessageOutput contract below, not the SDK.
// ----------------------------------------------------------------------------

import { createOpencodeClient } from '@opencode-ai/sdk';

const BACKEND = process.env.ATELIER_BACKEND_URL || 'http://localhost:3001';

export interface ServeRunInfo {
  runId: string;
  worktreePath: string;
  port: number;
  password: string;
}

export interface ServeMessageInput {
  runId: string;
  /** Persona key — must match a Persona literal in backend/src/opencode/personas.ts */
  persona: string;
  /** Full prompt body sent to the session as a user message. */
  prompt: string;
  /** Optional model override (e.g. "primary/MiniMax-M2.7"). Defaults to whatever
   *  the bootstrapped opencode.json declares as `model`. */
  model?: string;
}

export interface ServeMessageOutput {
  text: string;
  promptTokens: number;
  completionTokens: number;
  /** opencode session id — useful for follow-up turns and audit. */
  sessionId: string;
  /** Aggregate cost in USD if the SDK reports it; 0 otherwise. */
  costUsd: number;
}

export async function getServeRunInfo(runId: string): Promise<ServeRunInfo> {
  const response = await fetch(`${BACKEND}/api/opencode/run/${encodeURIComponent(runId)}`);
  if (!response.ok) {
    throw new Error(`No opencode server registered for run ${runId} (HTTP ${response.status})`);
  }
  return await response.json() as ServeRunInfo;
}

function basicAuthHeader(password: string): string {
  // Backend uses HTTP Basic with username "opencode"; matches
  // backend/src/opencode/lifecycle.ts and backend/src/opencode/sessions.ts.
  return 'Basic ' + Buffer.from('opencode:' + password).toString('base64');
}

function buildClient(info: ServeRunInfo) {
  return createOpencodeClient({
    baseUrl: `http://127.0.0.1:${info.port}`,
    headers: { Authorization: basicAuthHeader(info.password) },
  });
}

/** Parse "primary/MiniMax-M2.7" into { providerID: "primary", modelID: "MiniMax-M2.7" }.
 *  Returns null when the input doesn't contain the expected separator — caller
 *  then falls back to whatever opencode.json's default `model` is set to. */
function parseModelRef(model: string | undefined): { providerID: string; modelID: string } | null {
  if (!model) return null;
  const slash = model.indexOf('/');
  if (slash <= 0 || slash === model.length - 1) return null;
  return { providerID: model.slice(0, slash), modelID: model.slice(slash + 1) };
}

async function ensureSession(runId: string, persona: string): Promise<string> {
  const sessionResp = await fetch(
    `${BACKEND}/api/opencode/run/${encodeURIComponent(runId)}/session/${encodeURIComponent(persona)}`,
    { method: 'POST' },
  );
  if (!sessionResp.ok) {
    const text = await sessionResp.text().catch(() => '');
    throw new Error(
      `Failed to ensure opencode session for ${persona}: HTTP ${sessionResp.status} ${text.slice(0, 200)}`,
    );
  }
  const { sessionId } = await sessionResp.json() as { sessionId: string };
  return sessionId;
}

export async function sendDeveloperPrompt(input: ServeMessageInput): Promise<ServeMessageOutput> {
  const info = await getServeRunInfo(input.runId);
  const client = buildClient(info);

  // Reuse the per-persona session created by backend/src/opencode/sessions.ts.
  // The backend's run registry caches sessionId per persona, so this is a
  // cheap lookup after the first call.
  const sessionId = await ensureSession(input.runId, input.persona);

  const modelRef = parseModelRef(input.model);
  const result = await client.session.prompt({
    path: { id: sessionId },
    body: {
      parts: [{ type: 'text', text: input.prompt }],
      ...(modelRef ? { model: modelRef } : {}),
    },
  });

  if (result.error) {
    const errBody = JSON.stringify(result.error).slice(0, 500);
    throw new Error(
      `opencode session.prompt failed (sessionId=${sessionId}, persona=${input.persona}): ${errBody}`,
    );
  }
  if (!result.data) {
    throw new Error(
      `opencode session.prompt returned empty response (sessionId=${sessionId}, persona=${input.persona})`,
    );
  }

  const { info: assistantMessage, parts } = result.data;

  // Concatenate all "text" parts in order — that's the assistant's reply body.
  // Other part types (tool calls, files, reasoning) are intentionally ignored
  // here; Task 7 only needs the plain reply text + usage.
  const text = parts
    .filter((p): p is Extract<typeof p, { type: 'text' }> => p.type === 'text')
    .map((p) => p.text)
    .join('');

  return {
    text,
    promptTokens: assistantMessage.tokens?.input ?? 0,
    completionTokens: assistantMessage.tokens?.output ?? 0,
    costUsd: assistantMessage.cost ?? 0,
    sessionId,
  };
}

export interface AgentPromptInput {
  runId: string;
  /** Persona key used to name/reuse the opencode session (e.g. 'researcher-architecture'). */
  personaKey: string;
  /** Full persona system-prompt text, injected into the user message body. */
  personaText: string;
  /** The task-specific user message body. */
  userPrompt: string;
  /** Optional model override: "primary/ModelName". */
  model?: string;
}

/** Send a read-only analyst prompt to an existing per-run opencode session.
 *  The model is instructed not to write files and to respond with JSON only.
 *  Returns the raw text — callers parse it with withJsonRetry. */
export async function sendAgentPrompt(input: AgentPromptInput): Promise<string> {
  const { runId, personaKey, personaText, userPrompt, model } = input;
  const prompt = [
    'ANALYSIS MODE: You must not write, edit, or delete any files.',
    'Use your read, grep, glob, and bash tools to explore the codebase.',
    '',
    personaText,
    '',
    userPrompt,
    '',
    'IMPORTANT: Respond with ONLY valid JSON. No prose, no markdown fences, no text outside the JSON structure.',
  ].join('\n');

  const result = await sendDeveloperPrompt({ runId, persona: personaKey, prompt, model });
  return result.text;
}
