// Wraps @opencode-ai/sdk for sending a developer prompt to an existing per-run
// opencode session and collecting back the assistant text + token usage.
//
// The per-run server is started by the workflow's startRunOpencode activity
// (Task 5). We resolve port/password from the backend, lazily create or reuse
// the developer session via the backend's session-ensure endpoint, send the
// prompt directly to the opencode HTTP server using the SDK, and return a
// stable result shape.
//
// ----------------------------------------------------------------------------
// SDK SHAPE NOTES — discovered from @opencode-ai/sdk@1.14.25
// ----------------------------------------------------------------------------
// The SDK is auto-generated by @hey-api/openapi-ts and differs from the plan
// snippet. Key facts a future maintainer needs:
//
//   * Import: `import { createOpencodeClient, type OpencodeClient } from '@opencode-ai/sdk'`
//     There is also `new OpencodeClient(...)` exported, but it expects an
//     internal `_HeyApiClient` instance — the supported entry point is the
//     factory `createOpencodeClient(config)`.
//
//   * Constructor config (`Config & { directory?: string }`):
//       - `baseUrl: string`              — e.g. "http://127.0.0.1:<port>"
//       - `headers?: Record<...>`        — used here for Basic auth
//       - `auth?: AuthToken | (auth) => ...` — only relevant for endpoints
//                                              that declare a security scheme;
//                                              opencode serve uses Basic auth
//                                              and the OpenAPI doesn't declare
//                                              that scheme, so we add the
//                                              Authorization header directly.
//
//   * Send a message: `client.session.prompt({ path: { id }, body: { parts, model? } })`
//     - `path.id` is the session ID
//     - `body.parts` is `Array<TextPartInput | FilePartInput | ...>` —
//       a plain text prompt becomes `[{ type: 'text', text: '...' }]`
//     - `body.model` is `{ providerID: string; modelID: string }` (NOT a
//       slash-separated string). We parse "primary/MiniMax-M2.7" into the
//       struct form.
//
//   * Response shape (default responseStyle is "fields"):
//       { data: { info: AssistantMessage; parts: Part[] } | undefined,
//         error: ... | undefined,
//         request, response }
//     - `info` is an AssistantMessage with `cost: number` and
//       `tokens: { input, output, reasoning, cache: { read, write } }`.
//     - `parts` is a Part[] union. The assistant's plain reply lives in
//       parts whose `type === 'text'`; we concatenate all text parts.
//
// SDK upgrades only need this file edited; downstream callers (Task 7) depend
// on the ServeMessageInput / ServeMessageOutput contract below, not the SDK.
// ----------------------------------------------------------------------------

import { createOpencodeClient } from '@opencode-ai/sdk';
import { stripThinking } from './callLLM.js';

const BACKEND = process.env.ATELIER_BACKEND_URL || 'http://localhost:3001';
const AGENT_PROMPT_TIMEOUT_MS = 3 * 60 * 1000;
const runPromptQueues = new Map<string, Promise<void>>();

export interface ServeRunInfo {
  runId: string;
  worktreePath: string;
  port: number;
  password: string;
}

export interface ServeMessageInput {
  runId: string;
  /** Persona key — must match a Persona literal in backend/src/opencode/personas.ts */
  persona: string;
  /** Full prompt body sent to the session as a user message. */
  prompt: string;
  /** Optional model override (e.g. "primary/MiniMax-M2.7"). Defaults to whatever
   *  the bootstrapped opencode.json declares as `model`. */
  model?: string;
  /** Agent pane that should receive opencode SSE progress for this prompt. */
  progressAgentId?: string;
}

export interface ServeMessageOutput {
  text: string;
  promptTokens: number;
  completionTokens: number;
  /** opencode session id — useful for follow-up turns and audit. */
  sessionId: string;
  /** Aggregate cost in USD if the SDK reports it; 0 otherwise. */
  costUsd: number;
}

export async function getServeRunInfo(runId: string): Promise<ServeRunInfo> {
  const response = await fetch(`${BACKEND}/api/opencode/run/${encodeURIComponent(runId)}`);
  if (!response.ok) {
    throw new Error(`No opencode server registered for run ${runId} (HTTP ${response.status})`);
  }
  return await response.json() as ServeRunInfo;
}

function basicAuthHeader(password: string): string {
  // Backend uses HTTP Basic with username "opencode"; matches
  // backend/src/opencode/lifecycle.ts and backend/src/opencode/sessions.ts.
  return 'Basic ' + Buffer.from('opencode:' + password).toString('base64');
}

function buildClient(info: ServeRunInfo) {
  return createOpencodeClient({
    baseUrl: `http://127.0.0.1:${info.port}`,
    headers: { Authorization: basicAuthHeader(info.password) },
  });
}

/** Parse "primary/MiniMax-M2.7" into { providerID: "primary", modelID: "MiniMax-M2.7" }.
 *  Returns null when the input doesn't contain the expected separator — caller
 *  then falls back to whatever opencode.json's default `model` is set to. */
export function parseModelRef(model: string | undefined): { providerID: string; modelID: string } | null {
  if (!model) return null;
  const slash = model.indexOf('/');
  if (slash <= 0 || slash === model.length - 1) return null;
  return { providerID: model.slice(0, slash), modelID: model.slice(slash + 1) };
}

async function ensureSession(runId: string, persona: string): Promise<string> {
  const sessionResp = await fetch(
    `${BACKEND}/api/opencode/run/${encodeURIComponent(runId)}/session/${encodeURIComponent(persona)}`,
    { method: 'POST' },
  );
  if (!sessionResp.ok) {
    const text = await sessionResp.text().catch(() => '');
    throw new Error(
      `Failed to ensure opencode session for ${persona}: HTTP ${sessionResp.status} ${text.slice(0, 200)}`,
    );
  }
  const { sessionId } = await sessionResp.json() as { sessionId: string };
  return sessionId;
}

async function emitAgentText(agentId: string, text: string): Promise<void> {
  await emitAgentEvent(agentId, { kind: 'text', text });
}

async function emitAgentEvent(agentId: string, event: Record<string, unknown>): Promise<void> {
  try {
    await fetch(`${BACKEND}/api/agent/event`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id: agentId, event }),
    });
  } catch {
    // UI progress is best-effort; the actual agent call should continue.
  }
}

function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(`${label} timed out after ${Math.round(ms / 1000)}s`)), ms);
    promise.then(
      (value) => { clearTimeout(timer); resolve(value); },
      (err) => { clearTimeout(timer); reject(err); },
    );
  });
}

async function withRunPromptSlot<T>(runId: string, fn: () => Promise<T>): Promise<T> {
  const previous = runPromptQueues.get(runId) ?? Promise.resolve();
  let release!: () => void;
  const current = new Promise<void>((resolve) => { release = resolve; });
  const stored = previous.catch(() => {}).then(() => current);
  runPromptQueues.set(runId, stored);

  await previous.catch(() => {});
  try {
    return await fn();
  } finally {
    release();
    if (runPromptQueues.get(runId) === stored) {
      runPromptQueues.delete(runId);
    }
  }
}

function summarizeOpencodeInput(input: unknown): unknown {
  if (!input || typeof input !== 'object') return input;
  const obj = input as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const key of ['file', 'path', 'pattern', 'query', 'command', 'description', 'url']) {
    if (typeof obj[key] === 'string') out[key] = obj[key];
  }
  return Object.keys(out).length > 0 ? out : obj;
}

function startOpencodeEventBridge(client: any, sessionId: string, agentId: string): () => void {
  const controller = new AbortController();
  const seenToolStates = new Map<string, string>();

  void (async () => {
    try {
      const result = await client.event.subscribe({ signal: controller.signal });
      for await (const data of result.stream) {
        if (controller.signal.aborted) break;
        const payload = (data as any)?.payload;
        if (!payload || typeof payload.type !== 'string') continue;

        if (payload.type === 'message.part.updated') {
          const part = payload.properties?.part;
          if (!part || part.sessionID !== sessionId) continue;

          if (part.type === 'reasoning') {
            const text = payload.properties?.delta ?? part.text;
            if (typeof text === 'string' && text.trim()) {
              await emitAgentEvent(agentId, { kind: 'thinking', text, ts: Date.now() });
            }
            continue;
          }

          if (part.type === 'tool') {
            const toolId = part.callID || part.id;
            const state = part.state?.status ?? 'pending';
            const stateKey = `${state}:${part.state?.title ?? ''}:${part.state?.output?.length ?? 0}:${part.state?.error ?? ''}`;
            if (seenToolStates.get(toolId) === stateKey) continue;
            seenToolStates.set(toolId, stateKey);

            if (state === 'pending' || state === 'running') {
              await emitAgentEvent(agentId, {
                kind: 'tool_use',
                toolId,
                name: part.tool,
                input: summarizeOpencodeInput(part.state?.input),
                ts: Date.now(),
              });
            } else {
              await emitAgentEvent(agentId, {
                kind: 'tool_result',
                toolId,
                content: part.state?.output ?? part.state?.error ?? part.state?.title ?? state,
                isError: state === 'error',
                ts: Date.now(),
              });
            }
            continue;
          }
        }

        if (payload.type === 'session.status' && payload.properties?.sessionID === sessionId) {
          const status = payload.properties.status;
          if (status?.type === 'retry') {
            await emitAgentText(agentId, `\n↳ provider retry ${status.attempt}: ${status.message}`);
          }
        }

        if (payload.type === 'session.error' && payload.properties?.sessionID === sessionId) {
          await emitAgentEvent(agentId, {
            kind: 'stderr',
            text: `opencode session error: ${JSON.stringify(payload.properties.error ?? {}).slice(0, 500)}`,
            ts: Date.now(),
          });
        }
      }
    } catch (e) {
      if (!controller.signal.aborted) {
        await emitAgentEvent(agentId, {
          kind: 'stderr',
          text: `opencode event stream ended: ${e instanceof Error ? e.message : String(e)}`,
          ts: Date.now(),
        });
      }
    }
  })();

  return () => controller.abort();
}

export async function sendDeveloperPrompt(input: ServeMessageInput): Promise<ServeMessageOutput> {
  const info = await getServeRunInfo(input.runId);
  const client = buildClient(info);

  // Reuse the per-persona session created by backend/src/opencode/sessions.ts.
  // The backend's run registry caches sessionId per persona, so this is a
  // cheap lookup after the first call.
  const sessionId = await ensureSession(input.runId, input.persona);
  const stopEvents = input.progressAgentId
    ? startOpencodeEventBridge(client, sessionId, input.progressAgentId)
    : undefined;

  const modelRef = parseModelRef(input.model);
  let result;
  try {
    result = await client.session.prompt({
      path: { id: sessionId },
      body: {
        parts: [{ type: 'text', text: input.prompt }],
        ...(modelRef ? { model: modelRef } : {}),
      },
    });
  } finally {
    stopEvents?.();
  }

  if (result.error) {
    const errBody = JSON.stringify(result.error).slice(0, 500);
    throw new Error(
      `opencode session.prompt failed (sessionId=${sessionId}, persona=${input.persona}): ${errBody}`,
    );
  }
  if (!result.data) {
    throw new Error(
      `opencode session.prompt returned empty response (sessionId=${sessionId}, persona=${input.persona})`,
    );
  }

  const { info: assistantMessage, parts } = result.data;

  // Concatenate all "text" parts in order — that's the assistant's reply body.
  // Other part types (tool calls, files, reasoning) are intentionally ignored
  // here; Task 7 only needs the plain reply text + usage.
  const text = parts
    .filter((p): p is Extract<typeof p, { type: 'text' }> => p.type === 'text')
    .map((p) => p.text)
    .join('');

  return {
    text,
    promptTokens: assistantMessage.tokens?.input ?? 0,
    completionTokens: assistantMessage.tokens?.output ?? 0,
    costUsd: assistantMessage.cost ?? 0,
    sessionId,
  };
}

export interface AgentPromptInput {
  runId: string;
  /** Persona key used to name/reuse the opencode session (e.g. 'researcher-architecture'). */
  personaKey: string;
  /** Full persona system-prompt text, injected into the user message body. */
  personaText: string;
  /** The task-specific user message body. */
  userPrompt: string;
  /** Optional model override: "primary/ModelName". */
  model?: string;
}

/** Send a read-only analyst prompt to an existing per-run opencode session.
 *  The model is instructed not to write files and to respond with JSON only.
 *  Returns the raw text — callers parse it with withJsonRetry. */
export async function sendAgentPrompt(input: AgentPromptInput): Promise<string> {
  const { runId, personaKey, personaText, userPrompt, model } = input;
  const prompt = [
    'ANALYSIS MODE: You must not write, edit, or delete any files.',
    'Use your read, grep, glob, and bash tools to explore the codebase.',
    '',
    personaText,
    '',
    userPrompt,
    '',
    'IMPORTANT: Respond with ONLY valid JSON. No prose, no markdown fences, no text outside the JSON structure.',
  ].join('\n');

  await emitAgentText(personaKey, '\n↳ opencode session running…');
  const startedAt = Date.now();
  const heartbeat = setInterval(() => {
    const seconds = Math.max(1, Math.round((Date.now() - startedAt) / 1000));
    void emitAgentText(personaKey, `\n↳ still working (${seconds}s)…`);
  }, 10_000);
  try {
    await emitAgentText(personaKey, '\n↳ waiting for opencode prompt slot…');
    const result = await withRunPromptSlot(runId, async () => {
      await emitAgentText(personaKey, '\n↳ opencode prompt active…');
      return await withTimeout(
        sendDeveloperPrompt({ runId, persona: personaKey, prompt, model, progressAgentId: personaKey }),
        AGENT_PROMPT_TIMEOUT_MS,
        `opencode prompt for ${personaKey}`,
      );
    });
    await emitAgentText(personaKey, `\n↳ response received (${Math.round((Date.now() - startedAt) / 1000)}s)`);
    return stripThinking(result.text);
  } finally {
    clearInterval(heartbeat);
  }
}
